services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_MULTIPLE_DATABASES: product_db,customer_db,inventory_db,pricing_db,order_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-multi-db.sh:/docker-entrypoint-initdb.d/init-multi-db.sh
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 3s
      retries: 10

  product_service:
    build: .
    command: python -m services.product_service.main
    environment:
      DB_URL: postgresql://admin:secret@postgres:5432/product_db
      PRICING_PAIR_ADDR: tcp://pricing_service:5557
      INVENTORY_PAIR_ADDR: tcp://inventory_service:5557
    depends_on:
      postgres:
        condition: service_healthy

  customer_service:
    build: .
    command: python -m services.customer_service.main
    environment:
      DB_URL: postgresql://admin:secret@postgres:5432/customer_db
    depends_on:
      postgres:
        condition: service_healthy

  inventory_service:
    build: .
    command: python -m services.inventory_service.main
    environment:
      DB_URL: postgresql://admin:secret@postgres:5432/inventory_db
      PRODUCT_PUB_ADDR: tcp://product_service:5556
      ORDER_PUB_ADDR: tcp://order_service:5556
    depends_on:
      postgres:
        condition: service_healthy

  pricing_service:
    build: .
    command: python -m services.pricing_service.main
    environment:
      DB_URL: postgresql://admin:secret@postgres:5432/pricing_db
      PRODUCT_PUB_ADDR: tcp://product_service:5556
    depends_on:
      postgres:
        condition: service_healthy

  order_service:
    build: .
    command: python -m services.order_service.main
    environment:
      DB_URL: postgresql://admin:secret@postgres:5432/order_db
    depends_on:
      postgres:
        condition: service_healthy

  gateway_service:
    build: .
    command: python -m services.gateway_service.main
    ports:
      - "8000:8000"
    environment:
      PRODUCT_REP_ADDR: tcp://product_service:5555
      CUSTOMER_REP_ADDR: tcp://customer_service:5555
      INVENTORY_REP_ADDR: tcp://inventory_service:5555
      PRICING_REP_ADDR: tcp://pricing_service:5555
      ORDER_REP_ADDR: tcp://order_service:5555
    depends_on:
      - product_service
      - customer_service
      - inventory_service
      - pricing_service
      - order_service

volumes:
  pg_data:
